//! Rust bindings for the Blueye Robotics protocol definitions.
//!
//! Generated at build time from the repository's `protobuf_definitions/*.proto`
//! files via [`prost`]. All messages live in the `blueye.protocol` proto
//! package and are re-exported flat from the crate root.
//!
//! Every message also derives [`prost_reflect::ReflectMessage`], and
//! [`DESCRIPTORS`] exposes a runtime descriptor pool, so `google.protobuf.Any`
//! payloads can be decoded by type name when the concrete type is only known at
//! runtime.

mod generated {
    include!(concat!(env!("OUT_DIR"), "/blueye.protocol.rs"));
}

pub use generated::*;

/// Re-export of the [`prost::Message`] trait for encoding/decoding.
pub use prost::Message;
/// Re-export of [`prost_reflect`] for runtime reflection
/// (`DescriptorPool`, `DynamicMessage`, `ReflectMessage`, …).
pub use prost_reflect;
/// Re-export of well-known types (`Timestamp`, `Duration`, `Any`).
pub use prost_types;

/// Encoded `FileDescriptorSet` for the entire protocol, generated at build
/// time. Referenced by the `#[derive(ReflectMessage)]` attribute on every
/// message and used to build [`DESCRIPTORS`].
pub const FILE_DESCRIPTOR_SET: &[u8] =
    include_bytes!(concat!(env!("OUT_DIR"), "/file_descriptor_set.bin"));

/// Lazily-decoded descriptor pool covering every `blueye.protocol` message and
/// its well-known-type dependencies. Look up messages by name and build
/// [`prost_reflect::DynamicMessage`]s when decoding `google.protobuf.Any`
/// payloads whose concrete type is only known at runtime.
pub static DESCRIPTORS: std::sync::LazyLock<prost_reflect::DescriptorPool> =
    std::sync::LazyLock::new(|| {
        prost_reflect::DescriptorPool::decode(FILE_DESCRIPTOR_SET)
            .expect("descriptor set generated by build.rs must decode")
    });
