name: CI build

on:
  push:
    branches:
      - port-protocol-to-protobuf
      - nuget-package

jobs:
  protolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/BluEye-Robotics/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build project and generate NuGet package
        run: |          
          dotnet pack Blueye.Protocol.Protobuf.csproj --version-suffix "ci.$GITHUB_RUN_NUMBER" -c Release -o out  

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./out/*.nupkg --skip-duplicate --no-symbols true