name: Trigger update in blueye.protocol

on:
  push:
    paths:
      - "protobuf_definitions/**"
      - "tcp_protocol.json"
      - "udp_protocol.json"
    branches:
      - "master"

jobs:
  trigger-blueye-protocol:
    runs-on: ubuntu-latest
    steps:
      - name: Create a repository dispatch event
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.CI_PAT }}" \
          https://api.github.com/repos/blueye-robotics/blueye.protocol/dispatches \
          -d '{"event_type":"protocol-update","client_payload":{"sha":"${{ github.sha }}"}}'
