name: Python CI build

on:
  push:
  release:
    types: [created]

jobs:
  build-python-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: "1.1.14"

      - name: Install dependencies
        working-directory: python_build
        run: poetry install

      - name: Generate proto-plus project
        run: |
          docker run \
          --mount type=bind,source=$(pwd)/protobuf_definitions/,destination=/in/ \
          --mount type=bind,source=$(pwd)/python_build/,destination=/out/ \
          --rm \
          --user $UID \
          gcr.io/gapic-images/gapic-generator-python:v0.40

      - name: Build package with poetry
        working-directory: python_build
        run: poetry build

      - name: Upload dist-folder
        uses: actions/upload-artifact@v2
        with:
          name: blueye.protocol-dist
          path: python_build/dist

      - name: Publish to PyPi
        if: ${{ github.event_name == 'release' }}
        working-directory: python_build
        run: poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
