name: Compile TypeScript Protobuf Definitions

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          cd protobuf_definitions
          npm init -y
          npm install -D ts-proto

      - name: Compile
        run: |
          cd protobuf_definitions
          mkdir -p ./out/ &&
          protoc *.proto --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_out=./out --ts_proto_opt=outputIndex=true

      - name: Publish compiled proto definitions
        uses: actions/upload-artifact@v4
        with:
          path: protobuf_definitions/out
