name: ProtocDock

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: ProtocDock Compile
        uses: valentin-kaiser/protocdock@master
        with:
          command: 'cd protobuf_definitions && rm -r ./gen/ && mkdir -p ./gen/ && protoc *.proto --plugin=ts-protoc-gen=$PROTOC_GEN_TS_PATH --grpc-web_out="import_style=typescript,mode=grpcweb:./gen/" --proto_path=./protobuf_definitions --ts_out=service=grpc-web:./gen/ --ts_opt=esModuleInterop=true --ts_opt=useOptionals=true --ts_opt=addGrpcMetadata=true --ts_opt=addGrpcWebImports=true'
          commit_message: '[GEN] Updated compiled proto definitions'

      - name: Publish compiled proto definitions
        uses: actions/upload-artifact@v4
        with:
          path: protobuf_definitions/gen
