name: Generate documentation

on:
  push:
    branches:
      - master

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Install protoc + protoc-gen-doc
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler
          go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@v1.5.1
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      - name: Create output directory
        run: mkdir -p docs
      - name: Generate documentation
        run: protoc --doc_out=docs --doc_opt=html,protocol.html --proto_path=protobuf_definitions protobuf_definitions/*.proto
      - name: Publish artifacts
        uses: fixpoint/azblob-upload-artifact@v4
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          container: protocoldefinitions
          name: docs
          path: docs
