name: Generate documentation

on:
  push:
    branches:
      - port-protocol-to-protobuf

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    container:
      image: pseudomuto/protoc-gen-doc:1.4.1
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - name: Print path
        run: echo "${{ github.workspace }}/protobuf_definitions"
      - name: List files
        run: ls -la
      - name: Generate documentation
        run: protoc --doc_out=docs --doc_opt=html,protocol.html --proto_path=protobuf_definitions protobuf_definitions/*.proto
      - name: List doc files
        run: ls -la docs

