name: Generate documentation

on:
  push:
    branches:
      - master

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    container:
      image: pseudomuto/protoc-gen-doc:1.5.1
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Print path
        run: echo "${{ github.workspace }}/protobuf_definitions"
      - name: Create output configDirectory
        run: mkdir -p docs
      - name: List files
        run: ls -la
      - name: Generate documentation
        run: protoc --doc_out=docs --doc_opt=html,protocol.html --proto_path=protobuf_definitions protobuf_definitions/*.proto
      - name: List doc files
        run: ls -la docs
      - name: Publish artifacts
        uses: fixpoint/azblob-upload-artifact@v4
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          container: protocoldefinitions
          name: docs
          path: docs
